import type { Config } from "tailwindcss";
import containerQueries from '@tailwindcss/container-queries';

const config: Config = {
  darkMode: ["class"],
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./lib/**/*.{js,ts,jsx,tsx,mdx}",
    "./sanity/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    screens: {
      'xs': '320px',
      'xs-plus': '360px',
      'iphone-se': '375px',
      'iphone-mini': '375px',
      'iphone-x': '375px',
      'iphone-12': '390px',
      'iphone-14': '390px',
      'iphone-15': '393px',
      'iphone-16': '393px',
      'iphone-17': '393px',
      'iphone-xr': '414px',
      'iphone-11-max': '414px',
      'iphone-plus': '414px',
      'iphone-12-max': '428px',
      'iphone-15-max': '430px',
      'iphone-16-max': '440px',
      'iphone-17-max': '440px',
      'android-xs': '360px',
      'android-sm': '384px',
      'android-md': '393px',
      'android-lg': '412px',
      'android-xl': '430px',
      'android-fold': '344px',
      'fold-closed': '344px',
      'fold-open': '768px',
      'flip-closed': '260px',
      'flip-open': '390px',
      'sm': '640px',
      'tablet-sm': '600px',
      'tablet-nexus': '600px',
      'md': '768px',
      'ipad-mini': '768px',
      'ipad-air': '820px',
      'ipad': '810px',
      'android-tab': '800px',
      'ipad-pro-11': '834px',
      'ipad-pro-12': '1024px',
      'samsung-tab-s': '884px',
      'surface': '912px',
      'lg': '1024px',
      'xl': '1280px',
      '2xl': '1536px',
    },
    extend: {
      screens: {
        tall: { raw: '(min-height: 812px)' },
        'tall-max': { raw: '(min-height: 926px)' },
        'dynamic-island': { raw: '(min-height: 852px) and (min-width: 393px)' },
        'fold-landscape': { raw: '(min-width: 653px) and (max-width: 767px)' },
        'tablet-land': { raw: '(min-width: 1024px) and (max-height: 1366px)' },
        'can-hover': { raw: '(hover: hover) and (pointer: fine)' },
        touch: { raw: '(hover: none) and (pointer: coarse)' },
        'motion-safe': { raw: '(prefers-reduced-motion: no-preference)' },
        'motion-reduce': { raw: '(prefers-reduced-motion: reduce)' },
      },
      colors: {
        bs: {
          bg: "#0a0a0a",
          text: "#ffffff",
          muted: "#888888",
          panel: "#111111",
          panelSoft: "#151515",
          border: "#2b2b2b",
        },
      },
      fontFamily: {
        sans: ["var(--font-inter)", "system-ui", "sans-serif"],
      },
      maxWidth: {
        shell: "1360px",
      },
    },
  },
  plugins: [containerQueries],
};

export default config;
